# Generated by Django 4.2.3 on 2023-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_owner_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='values',
            field=models.CharField(blank=True, null=True),
        ),
    ]
