# Generated by Django 4.2.3 on 2023-12-28 18:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_options_job_type_alter_job_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('completed', 'COMPLETED')], default=core.models.StatusChoice['ANNOTATION'], max_length=32),
        ),
    ]
